import os
from google.adk.agents import LlmAgent
from google.adk.tools.agent_tool import AgentTool

LLM_MODEL = os.environ['LLM_MODEL']

root_agent = LlmAgent(
    model = LLM_MODEL,
    name = 'nl2cypher_agent',
    description="Seeks approval from the user for the query generated by the cypher_agent and takes relevant action based on the user's response",
    instruction=
    '''
    ''',
    tools=[]
)